SELECT SUM(HRG.SCORE) AS SCORE, HRE.EMP_NO, HRE.EMP_NAME, HRE.POSITION, HRE.EMAIL
    FROM HR_EMPLOYEES HRE JOIN HR_GRADE HRG
    ON HRE.EMP_NO = HRG.EMP_NO
    GROUP BY EMP_NO
    ORDER BY 1 DESC
    LIMIT 1